### ISSUE TITLE
ajaxcontroltoolkit older than version 15

### ISSUE THREAD

**Issue by chkuo2** [flight-tom/SqlWebAdmin#1]
using vs 2019 community, had some question about build. about ajaxcontroltoolkit older than version 15.
error message "
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown server tag 'ajaxToolkit:ToolkitScriptManager'.		C:\src\sqlwebadmin\SqlWebAdmin\viewTableData.aspx	136	
" 
Could you give me some suggestion ?

**Comment by flight-tom** [comment]
I have upgraded the solution to dotnet 4.8, and resolve the problem you are asking.
You can update and try.

**Comment by flight-tom** [comment]
BTW, after compilation fixed, you may run into a **runtime problem** about missing a COM component.
Just Google "_{10020200-E260-11CF-AE68-00AA004A34D5}_" the CLSID, you can find some solutions.
